### ISSUE TITLE
2个问题，咨询一下！一直报GC错误

### ISSUE THREAD

**Issue by zt9788** [eleme/HermesEventBus#10]
这两个问题都一直频繁出现（尤其在sony的一台机器上，其他的还好）

版本：compile 'xiaofei.library:hermes-eventbus:0.2.0'

 > 一个process进程，连接主程序，主要post消息 _thread ==>（in main thread）_
 >是我的配置问题，还是设备问题？
 >这两个问题，出现的频率基本上一小时~两小时出现一次

**UPDATE：**
  >通常在使用，高德地图或其他软件时发生
  >另外程序内部，经常报**DeadObjectException**，所以主程序内部通信采用EventBus发送消息，但是在Activity-create时仍用HermesEventBus-register（这个问题，基本所有的机器都提示，改了之后没有）

问题1:
`
FINGERPRINT=google/razor/flo:4.3/JWR66N/711294:user/dev-keys
HARDWARE=vbox86
UNKNOWN=unknown
RADIO=unknown
BOARD=flo
versionCode=3
PRODUCT=razor
versionName=1.0.0
DISPLAY=JWR66N
USER=Tracker
HOST=vpbs6.mtv.corp.google.com
DEVICE=Tracker
TAGS=test-keys
MODEL=Nexus 11
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=true
CPU_ABI3=unknown
ID=JWR66N
SERIAL=unknown
MANUFACTURER=asus
BRAND=Google

**java.lang.IllegalStateException: An error occurred in the GC.**
        at android.os.Parcel.readException(Parcel.java:1473)
        at android.os.Parcel.readException(Parcel.java:1419)
        at xiaofei.library.hermes.internal.IHermesService$Stub$Proxy.gc(IHermesService.java:168)
        at xiaofei.library.hermes.internal.Channel.gc(Channel.java:240)
        at xiaofei.library.hermes.util.HermesGc.gc(HermesGc.java:92)
        at xiaofei.library.hermes.util.HermesGc.register(HermesGc.java:99)
        at xiaofei.library.hermes.Hermes.getProxy(Hermes.java:97)
        at xiaofei.library.hermes.Hermes.getInstanceWithMethodNameInService(Hermes.java:163)
        at xiaofei.library.hermes.Hermes.getInstanceInService(Hermes.java:126)
        at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:287)
        at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:284)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1110)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1127)
        at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5055)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)`

问题2：

`SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@f3b577b
versionCode=2
BOARD=msm8994
BOOTLOADER=s1
TYPE=user
ID=32.2.A.0.305
BRAND=Sony
TAG=Build
SERIAL=BH9004RC4C
HARDWARE=qcom
SUPPORTED_ABIS=[Ljava.lang.String;@50de998
CPU_ABI=arm64-v8a
RADIO=unknown
IS_DEBUGGABLE=false
MANUFACTURER=Sony
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@a12130a
TAGS=release-keys
CPU_ABI2=
UNKNOWN=unknown
USER=BuildUser
FINGERPRINT=Sony/E6683/E6683:6.0.1/32.2.A.0.305/724807262:user/release-keys
HOST=BuildHost
PRODUCT=E6683
DEVICE=E6683

**java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermes.internal.IHermesService.gc(java.util.List)' on a null object reference**
        at xiaofei.library.hermes.internal.Channel.gc(Channel.java:240)
        at xiaofei.library.hermes.util.HermesGc.gc(HermesGc.java:92)
        at xiaofei.library.hermes.util.HermesGc.register(HermesGc.java:99)
        at xiaofei.library.hermes.Hermes.getProxy(Hermes.java:97)
        at xiaofei.library.hermes.Hermes.getInstanceWithMethodNameInService(Hermes.java:163)
        at xiaofei.library.hermes.Hermes.getInstanceInService(Hermes.java:126)
        at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:287)
        at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:284)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1227)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1244)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by Xiaofei-it** [comment]
有没有导致程序崩溃？理论上不会导致程序崩溃，但如果造成崩溃，请告诉我。

一般这种情况是子进程在结束进程前没有调用`HermesEventBus.destroy()`导致的， 但一般不会造成崩溃，会打印一些异常信息。`DeadObjectException`就是典型的这类异常。

但我们还是要看看你反映的另外两个异常的产生原因。看起来是这样子的，子进程建立连接后，子进程试图获取主进程的MainService实例，但这个时候有一个进程不存在了。不过我就很奇怪，为什么会发生这种情况？我是不是什么地方判断错误了？希望你帮忙分析一下。你是否在主进程调用`HermesEventBus.connectApp()`？你是否同时使用了Hermes库？

异常的具体原因如下：子进程A连接主进程B成功后，子进程A试图获取主进程B的MainService实例，获取成功后，在本地（子进程A）注册这个实例（获取的其他进程的对象都会在本地有一个对应的对象，这些对象注册在ObjectCenter内）。注册前，Hermes库会扫描之前注册的对象，如果发现某个对象已经被回收，就会通知这个对象原本属于的进程，告诉它“我不需要这个对象了，你不必为我持有这个对象的引用”。但是在这个时候：

1、如果那个进程不存在了，就会报第二个异常。我就觉得很奇怪，按理说，那个时候子进程之前不会注册任何对象，除非你之前连接过主进程，而后来那个进程死了，你这次连接了一个新的主进程，或者你还使用了Hermes库吗？

2、如果那个进程存在，但那个进程的ObjectCenter已经不持有那个对象的引用，那么就会抛出第一个异常。但是我想不出这种情况的发生原因。你最好提供一下你的具体场景：有几个进程，怎么连接的。

**Comment by zt9788** [comment]
多谢回复！！！
1.目前消息类的，只引用了：hermes-eventbus:0.2.0

2.是这样的，开始的时候，我在<Service .... process=“pageName” >的oncreate方法中确实调用了connectapp（==>App），然后现在我删掉了[这个地方应该是我的配置有问题吧？在同一个app里面
地方应该是我的配置有问题吧？在同一个app里面引用了connectapp可能是？目前已经删掉了]（但是依然有GC异常），我现在利用Thread.UncaughtExceptionHandler来抓获整体异常，目前程序会提示错误信息，但是也有闪退情况（在miui上基本没出现过，主要出现的就是**sony**和**google**的机器）[**因为目前拿到的都是回传的崩溃日志，即使沟通了一下，还是不能太确定程序是否完全崩溃**]

3.程序我自己一个就2个进程,一个主进程,一个process-service进程,外加hermes-eventbus的一个service,其他没有了
4.在activity的destroy里面，我已经判断了，如果register，就unregister (BaseActivity)
5.app集成了百度SDK，一般在访问其他含有定位程序时，容易出现（不过，我这边也没复现~~所以我也无奈了！！要是在调试过程中复现了的话就好办了）

**Comment by Xiaofei-it** [comment]
在访问其他app，或者按home让你的app在后台运行的时候，你的app容易被杀死。在这种情况下很容易发生之前说的崩溃。建议你在进程杀死前调用`HermesEventBus.getDefault().destroy()`，不光是调用unregister。我已经在readme里更新了用法。至于怎么判断进程被杀死，这个要看你业务需求，你只能自己琢磨一下。不过如果这个异常对用户不可见，那你可以忽略，外面搞个ExceptionHandler捕捉就可以了。

另外，同一个app内，不要用connectApp，用init方法就可以了。

**Comment by Xiaofei-it** [comment]
如果你的子进程里面只有一个service，那你可以在Service的onDestroy()里调用`HermesEventBus.getDefault().destroy()`。

我当初抛出异常是为了让这个库的使用者养成一个好的使用习惯。如果不那么做，有的时候出了体验上的bug也无从探查。如果确实困扰到你，并且导致app崩溃，我可以把这些异常在内部捕捉。

等你查出原因后，我再看要不要改进。

**Comment by zt9788** [comment]
好的，非常感谢!我先试一下，如果还有这个问题，我在反馈！！
万分感谢！

**Comment by Xiaofei-it** [comment]
你试了之后有结果了吗？

**Comment by zt9788** [comment]
一直想给你回复，这两天github的样式表，我这边一直加载不上来，所有才都不好用！
是这样的，目前的测试结果
1.已经在service的destroy中加入了HermesEventBus.getDefault().destroy();
目前报告GC错误相对比以前少了很多，但是sony上还存在，在一台小米2上也出现一次！

**Comment by Xiaofei-it** [comment]
好的，谢谢！

我最近完善一下这些异常信息。

**Comment by zt9788** [comment]
不客气，已经帮我解决很大问题了！

**Comment by Xiaofei-it** [comment]
虽然这些异常不会导致程序崩溃，只是会打印日志，不过我还是稍微改了一下。

你可以试试最新版v0.3.0，新版本处理异常比较温和。

**Comment by zt9788** [comment]
好的!今天回去试试!
