### ISSUE TITLE
Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register

### ISSUE THREAD

**Issue by dongfanglinglong** [eleme/HermesEventBus#19]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register(int, xiaofei.library.hermeseventbus.ISubService)' on a null object reference
       at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:288)
       at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:284)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1305)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1322)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by Xiaofei-it** [comment]
How and how often does this exception occur?

This is the first time I have encountered this exception.

**Comment by dongfanglinglong** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register(int, xiaofei.library.hermeseventbus.ISubService)' on a null object reference
       at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:288)
       at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:284)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1264)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1281)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5917)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by Xiaofei-it** [comment]
这个问题我下一次进行改善。谢谢反馈！

**Comment by Xiaofei-it** [comment]
另外，你是怎么使用的？感觉很奇怪。之前反馈中从没看到这个问题。

**Comment by dongfanglinglong** [comment]
我一个app中有两个进程，一个UI，一个service，然后就要了app内进程间通讯；

此外做了一个进程包含措施，这又是一个进程，用来保活UI进程和service 进程，使用https://github.com/Marswin/MarsDaemon 这个开源库；

 

 

发件人: Xiaofei [mailto:notifications@github.com] 
发送时间: 2017年1月4日 15:09
收件人: eleme/HermesEventBus <HermesEventBus@noreply.github.com>
抄送: dongfanglinglong <dongfanglinglong@gmail.com>; Author <author@noreply.github.com>
主题: Re: [eleme/HermesEventBus] Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register (#19)

 

另外，你是怎么使用的？感觉很奇怪。之前反馈中从没看到这个问题。

**Comment by Xiaofei-it** [comment]
真的很奇怪啊，我这个问题先放着，看看有没有别人反馈。线上环境之前从没发现这个问题。可能和你用了其他库有关，我以后再查吧。

本来我想在那里做一个非空判断，不过这样就破坏了本来的逻辑，改动太大，可能会造成页面卡顿。

**Comment by dongfanglinglong** [comment]
嗯，我再等一段时间吧，再不行我就自己改吧

 

 

发件人: Xiaofei [mailto:notifications@github.com] 
发送时间: 2017年1月4日 18:18
收件人: eleme/HermesEventBus <HermesEventBus@noreply.github.com>
抄送: dongfanglinglong <dongfanglinglong@gmail.com>; Author <author@noreply.github.com>
主题: Re: [eleme/HermesEventBus] Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register (#19)

 

真的很奇怪啊，我这个问题先放着，看看有没有别人反馈。线上环境之前从没发现这个问题。可能和你用了其他库有关，我以后再查吧。

本来我想在那里做一个非空判断，不过这样就破坏了本来的逻辑，改动太大，可能会造成页面卡顿。

**Comment by liujianying** [comment]
我也遇到一样的问题
-----Crash Log Begin-----
    java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register(int, xiaofei.library.hermeseventbus.ISubService)' on a null object reference
        at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:291)
        at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:288)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1225)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1242)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5441)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
    
    -----Crash Log End-----

**Comment by Leney** [comment]
同样有这样的问题：

 xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:291)
--
 xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:288)
 android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1738)
 android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1770)
 android.os.Handler.handleCallback(Handler.java:873)
 android.os.Handler.dispatchMessage(Handler.java:99)
 android.os.Looper.loop(Looper.java:193)
 android.app.ActivityThread.main(ActivityThread.java:6806)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by CnyNer** [comment]
我也存在这个问题，望解决。线上很多这个bug。

**Comment by zkq49099** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register(int, xiaofei.library.hermeseventbus.ISubService)' on a null object reference
        at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:291)
        at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:288)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1738)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1770)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
同样的问题报道

**Comment by lygdhy** [comment]
我也遇到了，必现

FATAL EXCEPTION: main
                                                    Process: com.zwoasi.asiair:air, PID: 14395
                                                    java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register(int, xiaofei.library.hermeseventbus.ISubService)' on a null object reference
                                                    	at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:291)
                                                    	at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:288)
                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2210)
                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2242)
                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                    	at android.os.Looper.loop(Looper.java:219)
                                                    	at android.app.ActivityThread.main(ActivityThread.java:8673)
                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
