### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException An error occurred in the GC.

### ISSUE THREAD

**Issue by dongfanglinglong** [eleme/HermesEventBus#20]
Fatal Exception: java.lang.IllegalStateException: An error occurred in the GC.
       at android.os.Parcel.readException(Parcel.java:1476)
       at android.os.Parcel.readException(Parcel.java:1422)
       at xiaofei.library.hermes.internal.IHermesService$Stub$Proxy.gc(IHermesService.java:168)
       at xiaofei.library.hermes.internal.Channel.gc(Channel.java:240)
       at xiaofei.library.hermes.util.HermesGc.gc(HermesGc.java:92)
       at xiaofei.library.hermes.util.HermesGc.register(HermesGc.java:99)
       at xiaofei.library.hermes.Hermes.getProxy(Hermes.java:97)
       at xiaofei.library.hermes.Hermes.getInstanceWithMethodNameInService(Hermes.java:163)
       at xiaofei.library.hermes.Hermes.getInstanceInService(Hermes.java:126)
       at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:287)
       at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:284)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1151)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1168)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5333)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Xiaofei-it** [comment]
See [Here](https://github.com/eleme/HermesEventBus/issues/10)
