### ISSUE TITLE
android.os.DeadObjectException

### ISSUE THREAD

**Issue by wszyquan** [eleme/HermesEventBus#21]
使用hermesEventBus 框架，post 方法参数是string类型的不报错，但是使用了自定义的对象，报如下错误

01-12 16:07:27.103 12739-12761/xiaofei.library.hermeseventbustest E/HERMES_CALLBACK: Error occurs but does not crash the app.
                                                                                     android.os.DeadObjectException
                                                                                         at android.os.BinderProxy.transact(Native Method)
                                                                                         at xiaofei.library.hermes.internal.IHermesServiceCallback$Stub$Proxy.callback(IHermesServiceCallback.java:122)
                                                                                         at xiaofei.library.hermes.internal.HermesCallbackInvocationHandler.invoke(HermesCallbackInvocationHandler.java:57)
                                                                                         at java.lang.reflect.Proxy.invoke(Proxy.java:379)
                                                                                         at xiaofei.library.hermeseventbus.ISubService.post(ISubService.java)
                                                                                         at xiaofei.library.hermeseventbus.MainService.post(MainService.java:81)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at xiaofei.library.hermes.receiver.ObjectReceiver.invokeMethod(ObjectReceiver.java:57)
                                                                                         at xiaofei.library.hermes.receiver.Receiver.action(Receiver.java:125)
                                                                                         at xiaofei.library.hermes.HermesService$1.send(HermesService.java:54)
                                                                                         at xiaofei.library.hermes.internal.IHermesService$Stub.onTransact(IHermesService.java:70)
                                                                                         at android.os.Binder.execTransact(Binder.java:404)

**Comment by Xiaofei-it** [comment]
See #9 and #15.
