### ISSUE TITLE
java.lang.NoClassDefFoundError: xiaofei.library.concurrentutils.util.NonNullCondition

### ISSUE THREAD

**Issue by Jackchenys** [eleme/HermesEventBus#28]
AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.yishun, PID: 6752
                                                                        java.lang.NoClassDefFoundError: xiaofei.library.concurrentutils.util.NonNullCondition
                                                                            at xiaofei.library.concurrentutils.ObjectCanary.<init>(ObjectCanary.java:39)
                                                                            at xiaofei.library.concurrentutils.ObjectCanary.<init>(ObjectCanary.java:61)
                                                                            at xiaofei.library.hermeseventbus.HermesEventBus.<init>(HermesEventBus.java:56)
                                                                            at xiaofei.library.hermeseventbus.HermesEventBus.getDefault(HermesEventBus.java:63)
                                                                            at  com.yishun.manager.CMCCApplication.onCreate(CMCCApplication.java:421)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4438)
                                                                            at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5111)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
                                                                            at dalvik.system.NativeStart.main(Native Method)
楼主，报这个错误，怎么搞？？？

**Comment by Xiaofei-it** [comment]
有没有使用ProGuard？

将我的库全部keep试试看呢

**Comment by Jackchenys** [comment]
由于项目比较急，已近使用原生的aidl了

**Comment by Xiaofei-it** [comment]
好吧
