### ISSUE TITLE
为什么这边会报服务未绑定的错误

### ISSUE THREAD

**Issue by czgczg308** [eleme/HermesEventBus#39]
java.lang.IllegalStateException: Service Unavailable: You have not connected the service or the connection is not completed. You can set HermesListener to receive a callback when the connection is completed.
                                                                         at xiaofei.library.hermes.Hermes.checkBound(Hermes.java:87)
                                                                         at xiaofei.library.hermes.Hermes.getInstanceWithMethodNameInService(Hermes.java:139)
                                                                         at xiaofei.library.hermes.Hermes.getInstanceInService(Hermes.java:126)
                                                                         at xiaofei.library.hermes.Hermes.getInstance(Hermes.java:130)
                                                                         at com.yztc.itemcollect2.module.hermes.HermesActivity.onViewClicked(HermesActivity.java:50)
                                                                         at com.yztc.itemcollect2.module.hermes.HermesActivity_ViewBinding$3.doClick(HermesActivity_ViewBinding.java:59)
                                                                         at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                         at android.view.View.performClick(View.java:5207)
                                                                         at android.view.View$PerformClick.run(View.java:21177)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                         at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:163)

**Comment by czgczg308** [comment]
我自己 找到问题了
