### ISSUE TITLE
适配新版本support库

### ISSUE THREAD

**Issue by ElegantWang** [eleme/HermesEventBus#42]
``android.support.v7.app.ActionBarActivity``类从support库v26.0.2中删除了
导致错误:
```
java.lang.NoClassDefFoundError: android.support.v7.app.ActionBarActivity
                                                                                   at xiaofei.library.hermes.util.TypeUtils$1.<init>(TypeUtils.java:51)
                                                                                   at xiaofei.library.hermes.util.TypeUtils.<clinit>(TypeUtils.java:48)
                                                                                   at xiaofei.library.hermes.util.TypeCenter.register(TypeCenter.java:94)
                                                                                   at xiaofei.library.hermes.Hermes.register(Hermes.java:71)
                                                                                   at xiaofei.library.hermeseventbus.HermesEventBus.init(HermesEventBus.java:122)
```

**Comment by harmeetsingh-work** [comment]
Actually, this is issue in Hermes repo  `xiaofei.library.hermes.util.TypeUtils.java` at line `add(ActionBarActivity.class);`

For temporarily solving this issue, I created a empty class `android.support.v7.app.ActionBarActivity.java` and extend to `AppCompatActivity` and my app starting running again :)

```
package android.support.v7.app;

/**
 * Created by blackadmin on 07/10/17.
 */

public class ActionBarActivity extends AppCompatActivity {
}
```

Here I have created issue [issue-13](https://github.com/Xiaofei-it/Hermes/issues/13)

**Comment by moonljt521** [comment]
还得写个空类放那里，有点恶......
