### ISSUE TITLE
和Hermes混用时，HermesEventBus 崩溃

### ISSUE THREAD

**Issue by Lewis-0710** [eleme/HermesEventBus#43]
FATAL EXCEPTION: main
                                                                     Process: com.lewis.sample:DB, PID: 22211
                                                                     java.lang.NullPointerException: Attempt to invoke interface method 'void xiaofei.library.hermeseventbus.IMainService.register(int, xiaofei.library.hermeseventbus.ISubService)' on a null object reference
                                                                         at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java:291)
                                                                         at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java:288)
                                                                         at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1329)
                                                                         at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1346)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:179)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5739)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by Xiaofei-it** [comment]
你分开用的情况下，会出问题吗？

**Comment by Lewis-0710** [comment]
分开用不会出现问题，我已经换成ＲｘＢｕｓ了
