### ISSUE TITLE
依赖了过时的Activity

### ISSUE THREAD

**Issue by dennisjj** [eleme/HermesEventBus#45]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
                                                               at xiaofei.library.hermes.util.TypeUtils$1.<init>(TypeUtils.java:51)
                                                               at xiaofei.library.hermes.util.TypeUtils.<clinit>(TypeUtils.java:48)
                                                               at xiaofei.library.hermes.util.TypeCenter.register(TypeCenter.java:94)
                                                               at xiaofei.library.hermes.Hermes.register(Hermes.java:71)
                                                               at xiaofei.library.hermeseventbus.HermesEventBus.init(HermesEventBus.java:122)

**Comment by huaraco** [comment]
looks no one support this
