### ISSUE TITLE
java.lang.NullPointerException 	at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java) 	at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java)

### ISSUE THREAD

**Issue by XuMuFei** [eleme/HermesEventBus#47]
java.lang.NullPointerException
	at xiaofei.library.hermeseventbus.HermesEventBus$HermesListener.onHermesConnected(HermesEventBus.java)
	at xiaofei.library.hermes.internal.Channel$HermesServiceConnection.onServiceConnected(Channel.java)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1106)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1123)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by theaircrasher** [comment]
I do have exactly the same issue. Are there any updates on this issue?
