### ISSUE TITLE
这库是多久没有维护了居然报这个错.................

### ISSUE THREAD

**Issue by lxhtiamo** [eleme/HermesEventBus#53]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;

**Comment by mars-ma** [comment]
v7包不能更新到最新的版本，不能用了。。。

**Comment by json988** [comment]
package android.support.v7.app;

/**
 * Created by blackadmin on 07/10/17.
 */

public class ActionBarActivity extends AppCompatActivity {
}

**Comment by loveanao** [comment]
需要修改 hermes 源码  xiaofei.library.hermes.util.TypeUtils 源码	
        修改完成后，使用 module 依赖，亲测可用正常使用

	private static final HashSet<Class<?>> CONTEXT_CLASSES = new HashSet<Class<?>>() {
	    {
	        add(Context.class);
	        add(ActionBarActivity.class);
	        add(Activity.class);
	        add(AppCompatActivity.class);
	        add(Application.class);
	        add(FragmentActivity.class);
	        add(IntentService.class);
	        add(Service.class);
	    }
    };

    为

    private static final HashSet<Class<?>> CONTEXT_CLASSES = new HashSet<Class<?>>() {
        {
            add(Context.class);
            add(Activity.class);
            add(AppCompatActivity.class);
            add(Application.class);
            add(FragmentActivity.class);
            add(IntentService.class);
            add(Service.class);
        }
    };

**Comment by JcmeLs** [comment]
@loveanao 亲测可用

**Comment by mjsheng** [comment]
> ```
> 需要修改 hermes 源码  xiaofei.library.hermes.util.TypeUtils 源码	
>     修改完成后，使用 module 依赖，亲测可用正常使用
> 
> private static final HashSet<Class<?>> CONTEXT_CLASSES = new HashSet<Class<?>>() {
>     {
>         add(Context.class);
>         add(ActionBarActivity.class);
>         add(Activity.class);
>         add(AppCompatActivity.class);
>         add(Application.class);
>         add(FragmentActivity.class);
>         add(IntentService.class);
>         add(Service.class);
>     }
> };
> 
> 为
> 
> private static final HashSet<Class<?>> CONTEXT_CLASSES = new HashSet<Class<?>>() {
>     {
>         add(Context.class);
>         add(Activity.class);
>         add(AppCompatActivity.class);
>         add(Application.class);
>         add(FragmentActivity.class);
>         add(IntentService.class);
>         add(Service.class);
>     }
> };
> ```

我下了源码，但是找不到 xiaofei.library.hermes.util.TypeUtils 这个类，具体怎么操作呀！谢谢

**Comment by lotosbin** [comment]
@mjsheng 这个类是在 依赖的库 hermes 中的，不是这个仓储中，

**Comment by Aaron-the-coder** [comment]
> ```
> 需要修改 hermes 源码  xiaofei.library.hermes.util.TypeUtils 源码	
>     修改完成后，使用 module 依赖，亲测可用正常使用
> 
> private static final HashSet<Class<?>> CONTEXT_CLASSES = new HashSet<Class<?>>() {
>     {
>         add(Context.class);
>         add(ActionBarActivity.class);
>         add(Activity.class);
>         add(AppCompatActivity.class);
>         add(Application.class);
>         add(FragmentActivity.class);
>         add(IntentService.class);
>         add(Service.class);
>     }
> };
> 
> 为
> 
> private static final HashSet<Class<?>> CONTEXT_CLASSES = new HashSet<Class<?>>() {
>     {
>         add(Context.class);
>         add(Activity.class);
>         add(AppCompatActivity.class);
>         add(Application.class);
>         add(FragmentActivity.class);
>         add(IntentService.class);
>         add(Service.class);
>     }
> };
> ```

改完还是报错
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/ActionBarActivity;
        at xiaofei.library.hermes.util.TypeUtils$1.<init>(TypeUtils.java:51)
        at xiaofei.library.hermes.util.TypeUtils.<clinit>(TypeUtils.java:48)
        at xiaofei.library.hermes.util.TypeUtils.validateClass(TypeUtils.java:278)
        at xiaofei.library.hermes.util.TypeCenter.register(TypeCenter.java:94)
        at xiaofei.library.hermes.Hermes.register(Hermes.java:71)
        at xiaofei.library.hermeseventbus.HermesEventBus.init(HermesEventBus.java:125)
