### ISSUE TITLE
HERMES_CALLBACK Error occurs but does not crash the app.

### ISSUE THREAD

**Issue by CnyNer** [eleme/HermesEventBus#54]
2019-05-16 14:19:46.273 13679-13679/com.xxx.xxx E/HERMES_CALLBACK: Error occurs but does not crash the app.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1147)
        at xiaofei.library.hermes.internal.IHermesServiceCallback$Stub$Proxy.callback(IHermesServiceCallback.java:122)
        at xiaofei.library.hermes.internal.HermesCallbackInvocationHandler.invoke(HermesCallbackInvocationHandler.java:57)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy6.post(Unknown Source)
        at xiaofei.library.hermeseventbus.MainService.post(MainService.java:81)
        at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:209)
        at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:206)
        at xiaofei.library.hermeseventbus.HermesEventBus.actionInternal(HermesEventBus.java:172)
        at xiaofei.library.hermeseventbus.HermesEventBus.post(HermesEventBus.java:206)
        at xxx.xxxAccountManager$6.onNext(AccountManager.java:584)
        at xxx.xxx.AccountManager$6.onNext(AccountManager.java:574)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.tryEmit(ObservableFlatMap.java:262)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onNext(ObservableFlatMap.java:559)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:67)
        at xxx.xxx.network.base.BaseService$4.subscribe(BaseService.java:135)
        at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
        at io.reactivex.Observable.subscribe(Observable.java:10842)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:162)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by lyzhchc** [comment]
I found the same issue. I have 2 apps, when the main app post the message, the subscrible app did not receive with the subscrible app are not connecting the main app(maybe connected before but disconnected now). and i am trying reconnect the main app before this post issue occur.
