### ISSUE TITLE
android.os.DeadObjectException

### ISSUE THREAD

**Issue by stevefat** [eleme/HermesEventBus#9]
```
android.os.DeadObjectException
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java:496)
at xiaofei.library.hermes.internal.IHermesServiceCallback$Stub$Proxy.callback(IHermesServiceCallback.java:122)
at xiaofei.library.hermes.internal.HermesCallbackInvocationHandler.invoke(HermesCallbackInvocationHandler.java:57)
at java.lang.reflect.Proxy.invoke(Proxy.java:397)
at $Proxy6.post(Unknown Source)
at xiaofei.library.hermeseventbus.MainService.post(MainService.java:81)
at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:195)
at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:192)
at xiaofei.library.hermeseventbus.HermesEventBus.actionInternal(HermesEventBus.java:158)
at xiaofei.library.hermeseventbus.HermesEventBus.post(HermesEventBus.java:192)
```

**Comment by Xiaofei-it** [comment]
Does this exception crash your app? I think it does not. If so, please inform me.

This is a common exception, which occurs when a sub-process dies and the sub-process does not call `HermesEventBus.destroy()` before it dies.

If there is no way for you to call `HermesEventBus.destroy()` before a sub-process dies, you can let it be.

**Comment by stevefat** [comment]
这个可能是因为再```main ```的这个主线程 中接受的参数是个对象，这个对象中的某个属性是``` null```  ，然后```post()```  这个对象的时候发生了错误。根据我追踪，猜测是这样的

**Comment by Xiaofei-it** [comment]
你的具体代码我不清楚。不过最终导致这个异常的原因是：主进程向某个子进程发送事件，那个子进程之前已经死了，这样就会有异常。一般子进程很容易被系统杀死，之后又恢复。在你看来，只有一个子进程，其实Hermes已经记录了两个子进程，其中一个是死了的。给死的子进程发事件就会产生异常。不过不会导致程序崩溃。
你在子进程死亡前调用`HermesEventBus.getDefault().destroy()`就可以避免这种情况。

**Comment by stevefat** [comment]
好的，我试试，多谢

**Comment by Xiaofei-it** [comment]
现在可以了吗？

**Comment by stevefat** [comment]
嗯，现在没有问题了.

**Comment by Xiaofei-it** [comment]
好的。

**Comment by xx897589417** [comment]
你好，我的是基本上每次项目第一次运行，就会报这个异常，然后崩溃，然后再打开就好了
